### ISSUE TITLE
Forms not submitting data

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBMC_PL_GOOGLESPREADSHEETFORM#17]
According to the client some of the three forms (agent, lender and client) are not properly submitting their data.

> The Client form and Lender forms create a text error on submission while the Agent form does not. We have confirmed that the Agent form properly appends data to the Agent spreadsheet while the Client and Lender forms do not.

> We have also reset our permissions, as we usually do, and the problem persists.

**Comment by d4mation-** [comment]
Attempted to look into this on their Staging Site.

I logged in using the the credentials they gave us and when I attempted to open `Settings->Google Sheets Forms` I was immediately given a 500 Error. I wasn't able to get to where the Client said it was giving them problems.

Either there's an incompatibility with the Plugin's Code with the Theme or another Plugin on the Staging Site, or this could be a much larger issue with the Plugin itself.

I'll try to look through the plugin for any errors, but I noticed that the Client said the Staging Site wasn't up-to-date with what is on Live--It's just weird to me that I couldn't replicate their steps and instead got booted before I even got anywhere.

**Comment by d4mation-** [comment]
Within a local environment, I don't hit that 500 Error, but I also don't have the Client ID since that is stored to the WP Database.

I just realized that the credentials for me at the very end of the email coupled with the Staging FTP credentials were actually for the Live Site. On the Live site the 500 error I encountered doesn't exist. I see that the Staging Site we were given access to (`staging3`) isn't on the `Google App Redirect URIs` List, which is likely the cause of the 500 error.

I'll try to walk through the steps outlined in the email on the Live Site since I'm able to get in there properly and hopefully we can get this bug diagnosed.

**Comment by d4mation-** [comment]
I updated the Google API PHP Client (v1) to the latest Commit at the time of this writing and it seems to have fixed the error. I'll leave this open until we get Confirmation from the Client, but I just got an email for the Home to Home stuff so I think it is working once again.

![image](https://cloud.githubusercontent.com/assets/7770631/11913651/ba693cb6-a638-11e5-9601-cb1655da38a4.png)

**Comment by d4mation-** [comment]
Client has reported that everything has been resolved.
